#!/bin/bash
# ============================================================================
# STREAM VIEWER
# Copyright (C) 2026 Lazaros Chalkidis
# License: GPLv3
# =========================================================================

# stop the poll daemon on array stop
if [[ -f /var/run/streamviewer_poll.pid ]]; then
    kill $(cat /var/run/streamviewer_poll.pid) 2>/dev/null
    rm -f /var/run/streamviewer_poll.pid
fi
